# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build .NET sln
  pool:
      vmImage: $(vmImage)
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImage)
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: IntegrationTests
  displayName: Integration Tests
  dependsOn: Build
  pool:
      vmImage: $(vmImage)
  jobs:
  - job: intgrationtests
    displayName: Run integration tests
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'

    - task: PowerShell@2
      displayName: 'Starting Cosmos Emulator'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Pipeline.Workspace)
        script: |
           Write-Host "Starting CosmosDB Emulator"
           Import-Module "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator"
           Start-CosmosDbEmulator

    - task: DotNetCoreCLI@2
      displayName: "Integration Tests"
      inputs:
        command: test
        projects: "**/*.IntegrationTests.csproj"